### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#377]
Related to #358 

Suspect something like this would be good:

```js
class PaginatedTable extends React.Component {
  render() {
    const Paginate = this.props.paginationComponent;
    const Table = this.props.tableComponent;

    return (
      <div>
        <Table
          columns={...}
          rows={...}
        />
        <Paginate 
          page={this.state.page}
          onChange={this.onPageChange}
        />
      </div>
    )
  }
}

/// then: 

<PaginatedTable
  columns={...}
  rows={...}
  tableComponent={Table}
  paginationComponent={Paginate}
/>
```

**Comment by eliascodes** [comment]
Looks like this now, comments welcome:

![screen shot 2018-04-17 at 12 01 00](https://user-images.githubusercontent.com/12719553/38868247-512a85f8-423e-11e8-8419-47b5e38acd2c.png)

**Comment by astroash** [comment]
@eliascodes I believe you have missed your calling in life as a designer...

Few questions:
1. what does it look like if there's < 5 pages?
2. is the < button disabled in this view because you're on the 1st page? Does this look like > when on a page greater than 1? If so, is it jarring for a background to appear on this button in this case?

**Comment by eliascodes** [comment]
Temporarily de-prioritised in favour of bug fixes
