### ISSUE TITLE
🐛 Cannot differentiate between users with the same name

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-visitor#562]
Visitor login with name does not differentiate between users with the same name.

I wonder if this feature would be better implemented with email or matching names with year of birth

**Comment by eliascodes** [comment]
@edwardwptc 

The feature request in #536 was implemented, but then we discovered this problem with it. 

I think the suggestion to change this feature to matching on email makes sense since we know it will be globally unique. Do you think it would meet the needs of the users who requested this feature? Or should we think about a different solution?

**Comment by edwardwptc** [comment]
By "matching on email" do you mean it requires a user to type their name and then their email address into it? Or if there's multiple "John Smith"'s it will say "What is your email address?" 

Due to the nature of some CB's asking people their email addresses might not be very reliable, i.e. "My grandson set that up for me and I've forgotten what it was." and similar issues.

**Comment by astroash** [comment]
@edwardwptc the suggestion was to replace email with name. Would phone number be a better alternative?

If name is still preferred we have a few options:

- enter name and if there are multiple options a new box appears for email or number
- enter name, if there are multiples, box appears for year of birth, if there are still multiples sign in box appears for email or number.

NB: If we are adding multiple search input boxes for sign in, this is a more complicated change and may not be ready for release next week.

**Comment by edwardwptc** [comment]
Hi, 

Thanks. Preference would be Name as the easiest and straight forward way to do it. 99% of users won't have the same name. 

I think Name > If multiples > year of birth > If multiples > email address as you suggest. 

The logic here being that it involves least typing (drop down?) for year of birth. 

I take it by multiple search input boxes you mean the above sequential inputs that request further info if duplicates exist? If so, that's fine. I don't think it's a very major issue.
